 var data = 
    [
  {
    "Organization / Company": "Vizilare Technology Pvt Ltd",
    "Program Details": "Mechanical Engineering Internship",
    "Location": "Noida",
    "Duration": "6 Months ",
    "Stipend": "₹20,000–35,000/month (₹15–25k fixed + ₹5–10k incentives)",
    "Eligibility Criteria": "BE/B.Tech in Mechanical Engineering; ",
    "Skill Requirements": "AutoCAD, Autodesk Fusion 360, CAD, MS Office, Structural Analysis, Thermodynamics, Communication",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Informal Dress Code",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/mechanical-engineering-internship-in-multiple-locations-at-vizilare-technology-private-limited1756796047"
  },
  {
    "Organization / Company": "Pahwa Buildwell Pvt Ltd",
    "Program Details": "Draughtsman Internship",
    "Location": "Delhi",
    "Duration": "3 Months",
    "Stipend": "₹8,000–12,000/month",
    "Eligibility Criteria": "Diploma/BE/B.Tech in Architecture / Interior Design;",
    "Skill Requirements": "AutoCAD, Architectural Drafting, Attention to Detail, Teamwork",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/draughtmans-internship-in-delhi-at-pahwa-buildwell-private-limited1756991128"
  },
  {
    "Organization / Company": "Cyond",
    "Program Details": "Civil Engineering Internship",
    "Location": "Hyderabad",
    "Duration": "3 Months",
    "Stipend": "₹8,000/month",
    "Eligibility Criteria": "Diploma/BE/B.Tech in Civil Engineering;",
    "Skill Requirements": "Construction Management, Engineering Drawing, MS Office, Effective Communication",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/civil-engineering-internship-in-hyderabad-at-cyond1755078382"
  },
  {
    "Organization / Company": "ChargOps Systems Pvt Ltd",
    "Program Details": "Electronics Engineering Internship",
    "Location": "Jaipur, Noida",
    "Duration": "6 Months",
    "Stipend": "₹7,000–15,000/month (₹5–10k fixed + ₹2–5k incentives)",
    "Eligibility Criteria": "BE/B.Tech in Electronics / Electrical Engineering;",
    "Skill Requirements": "Analog Circuits, Circuit Design, PCB Design, Physics",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible Work Hours, Informal Dress Code, 5 Days/Week",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/electronics-engineering-internship-in-multiple-locations-at-chargops-systems-private-limited1757074407"
  },
  {
    "Organization / Company": "Narigiri's Connect To Universe Pvt Ltd",
    "Program Details": "Online Operating System (B.Tech) Tutoring Internship",
    "Location": "Work from Home",
    "Duration": "6 Months",
    "Stipend": "₹1,000–8,000/month",
    "Eligibility Criteria": "B.Tech; ",
    "Skill Requirements": "Operating Systems, Online Tutoring, Lesson Planning, Communication",
    "Perks & Benefits": "Certificate, Flexible Work Hours",
    "Mode / Work Type": "Part-time, Work-from-Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-online-operating-system-40btech-41-tutoring-internship-at-narigiris-connect-to-universe-private-limited1757072731"
  },
  {
    "Organization / Company": "Brilliant Approach Pvt Ltd",
    "Program Details": "CAD Design Internship",
    "Location": "Ahmedabad",
    "Duration": "3 Months",
    "Stipend": "₹5,000–10,000/month",
    "Eligibility Criteria": "Diploma/BE/B.Tech in Mechanical, Electrical, or Plumbing Engineering; ",
    "Skill Requirements": "AutoCAD, MEP Design, Drafting",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/cad-design-internship-in-ahmedabad-at-brilliant-approach-private-limited1756786567"
  },
  {
    "Organization / Company": "Planys Technologies Pvt Ltd",
    "Program Details": "Civil Engineering Internship",
    "Location": "Chennai",
    "Duration": "6 Months",
    "Stipend": "₹12,500–15,000/month",
    "Eligibility Criteria": "BE/B.Tech in Civil Engineering;",
    "Skill Requirements": "AutoCAD, MS Office, Video Editing",
    "Perks & Benefits": "Certificate, Free Snacks & Beverages",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/civil-engineering-internship-in-chennai-at-planys-technologies-private-limited1756723885"
  },
  {
    "Organization / Company": "Perfint Healthcare Pvt Ltd",
    "Program Details": "Mechanical Design Intern",
    "Location": "Chennai",
    "Duration": "6 Months",
    "Stipend": "₹10,000–15,000/month",
    "Eligibility Criteria": "BE/B.Tech Mechanical;",
    "Skill Requirements": "3D Printing, Autodesk Fusion 360, PTC Creo, SolidWorks, AutoCAD",
    "Perks & Benefits": "Certificate, Free Snacks & Beverages",
    "Mode / Work Type": "On-site",
    "Application Link": "http://internshala.com/internship/detail/mechanical-design-internship-in-chennai-at-perfint-healthcare-private-limited1756732510"
  },
  {
    "Organization / Company": "Achieve Point Pvt Ltd",
    "Program Details": "XML Conversion Specialist Intern",
    "Location": "Work from Home",
    "Duration": "2 Months",
    "Stipend": "₹6,000–12,000/month (₹5–10k fixed + ₹1–2k incentives)",
    "Eligibility Criteria": "B.Tech/Graduates; ",
    "Skill Requirements": "HTML, XML, JATS XML knowledge, Attention to Detail",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible Work Hours",
    "Mode / Work Type": "Work-from-Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-xml-conversion-specialist-internship-at-achieve-point-private-limited1757049502"
  },
  {
    "Organization / Company": "Electrobotics",
    "Program Details": "Robotics Internship: Develop robotic systems using Python, build prototypes with Raspberry Pi and Arduino, research Robotics/IoT trends, test systems, and collaborate in team meetings.",
    "Location": "Chennai, India",
    "Duration": "6 Months",
    "Stipend": "₹5,000 - 10,000/month",
    "Eligibility Criteria": "Strong English communication, Interest in robotics/AI, enjoys group work and working with children.",
    "Skill Requirements": "Arduino, IoT, Python, Raspberry Pi, Robotics",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, 5-day workweek",
    "Mode / Work Type": "Part-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/part-time-robotics-internship-in-chennai-at-electrobotics1756807775"
  },
  {
    "Organization / Company": "Cleantech Solar",
    "Program Details": "O&M Engineer Internship: Monitor PV systems via RMS portal, resolve performance issues, manage maintenance documentation, perform optimization analysis, and maintain CRM records.",
    "Location": "Faridabad, Delhi, Ghaziabad, Gurgaon, Noida, India",
    "Duration": "3 Months",
    "Stipend": "₹10,000 - 20,000/month",
    "Eligibility Criteria": "Available for 3-month full-time in-office internship, can start between 28th Aug'25 and 2nd Oct'25, own a laptop, based in or willing to relocate to Faridabad/Delhi/Ghaziabad/Gurgaon/Noida, interest in solar/O&M/asset management.",
    "Skill Requirements": "Adaptability, Attention to Detail, MS-Excel, Power Systems, Salesforce",
    "Perks & Benefits": "None specified",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/o-m-engineer-internship-in-multiple-locations-at-cleantech-solar1756377892"
  },
  {
    "Organization / Company": "Inorbvict Healthcare India",
    "Program Details": "WordPress Development Internship: Develop responsive WordPress websites, customize themes/plugins, convert Figma designs, optimize for SEO/performance, and provide technical support.",
    "Location": "Pune, India",
    "Duration": "3 Months",
    "Stipend": "₹5,999 - 6,000/month",
    "Eligibility Criteria": "Pursuing/recently completed degree in web development or related field, or non-technical background with strong WordPress/design skills.",
    "Skill Requirements": "Figma, Wix, WordPress",
    "Perks & Benefits": "Certificate, Letter of recommendation",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/wordpress-development-internship-in-pune-at-inorbvict-healthcare-india-private-limited1756989307"
  },
  {
    "Organization / Company": "BPG Renewables",
    "Program Details": "Engineer - Sales and Marketing (Biotechnology) Internship: Provide technical guidance to clients, use CRM/marketing tools, conduct market research, identify business opportunities, develop sales strategies, and maintain client relationships.",
    "Location": "Bangalore, India",
    "Duration": "6 Months",
    "Stipend": "₹15,000 - 27,000/month (Fixed: ₹5,000 - 7,000 + Incentive: ₹10,000 - 20,000)",
    "Eligibility Criteria": "Completed or in final year of relevant course.",
    "Skill Requirements": "Engineering Drawing, Marketing Strategies",
    "Perks & Benefits": "5-day workweek, Free snacks & beverages",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/engineer-sales-and-marketing-biotechnology-internship-in-bangalore-at-bpg-renewables1756465839"
  },
  {
    "Organization / Company": "Delhi Book Market",
    "Program Details": "React Native Development Internship: Develop mobile app features using React Native, integrate APIs/REST APIs, ensure user-friendly UI/UX, test and debug, and optimize app performance.",
    "Location": "Work from home",
    "Duration": "4 Months",
    "Stipend": "₹12,000 - 14,000/month",
    "Eligibility Criteria": " Interest in mobile app development.",
    "Skill Requirements": "APIs, React Native, REST API, UI & UX Design",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, Job offer (₹3LPA)",
    "Mode / Work Type": "Work from home",
    "Application Link": "Apply Here"
  },
  {
    "Organization / Company": "Entrily",
    "Program Details": "Web Development Internship: Develop and maintain WordPress websites, customize themes/plugins, design graphics with Canva, optimize performance, and troubleshoot issues.",
    "Location": "Work from home",
    "Duration": "2 Months",
    "Stipend": "₹5,000 - 9,000/month (Fixed: ₹3,000 - 5,000 + Incentive: ₹2,000 - 4,000)",
    "Eligibility Criteria": " Interest in web development.",
    "Skill Requirements": "Canva, WordPress",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-web-development-internship-at-entrily1757087895"
  },
  {
    "Organization / Company": "Unmannd Autonomy",
    "Program Details": "Founders Office Internship: Conduct market/technology research, compile reports, manage documentation, create SOPs, and support hiring/projects for UAV/aerospace initiatives.",
    "Location": "Bangalore, India",
    "Duration": "6 Months",
    "Stipend": "₹20,000/month",
    "Eligibility Criteria": "Bachelor’s in engineering or related field (or pursuing), strong organizational and communication skills, proficiency in productivity/AI tools, interest in UAVs/robotics/aerospace.",
    "Skill Requirements": "Effective Communication, Market Research, Project Management, Robotics, Scheduling, Technical Writing",
    "Perks & Benefits": "Certificate, Letter of recommendation, Informal dress code, Free snacks & beverages",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/founders-office-internship-in-bangalore-at-unmannd-autonomy1757085067"
  },
  {
    "Organization / Company": "Kampus Eats",
    "Program Details": "Android App Development Internship: Design and build app features, test and fix bugs, optimize performance, and contribute ideas for user experience.",
    "Location": "Delhi, India (Hybrid)",
    "Duration": "1 Month",
    "Stipend": "₹2,000 - 3,000/month",
    "Eligibility Criteria": " Interest in mobile app development.",
    "Skill Requirements": "Android, Dart, Firebase, Flutter, Node.js, REST API",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, Informal dress code",
    "Mode / Work Type": "Part-time, Hybrid",
    "Application Link": "https://internshala.com/internship/detail/part-time-android-app-development-internship-in-delhi-at-kampus-eats-private-limited1757075516"
  },
  {
    "Organization / Company": "Prem Prakash",
    "Program Details": "WordPress Development Internship: Develop WordPress websites with Elementor, customize themes/plugins, optimize SEO content, conduct keyword research, and use AI tools for content creation.",
    "Location": "Work from home",
    "Duration": "3 Months",
    "Stipend": "₹2,000 - 7,000/month (Fixed: ₹1,000 - 5,000 + Incentive: ₹1,000 - 2,000)",
    "Eligibility Criteria": " Knowledge of WordPress/Elementor, SEO fundamentals, familiarity with AI tools, reliable internet.",
    "Skill Requirements": "Adobe Photoshop, Canva, Content Writing, CSS, Figma, HTML, JavaScript, PHP, SEO, Web Design, WordPress",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-wordpress-development-internship-at-prem-prakash1757074348"
  },
  {
    "Organization / Company": "LazyDeveloper TechEd",
    "Program Details": "Flutter Development Internship: Develop cross-platform mobile apps using Flutter, integrate UI/functionality, optimize performance, and use Git for version control.",
    "Location": "Work from home",
    "Duration": "3 Months",
    "Stipend": "₹3,000 - 8,000/month",
    "Eligibility Criteria": " Interest in mobile app development.",
    "Skill Requirements": "Android, APIs, Cloud Firestore, Dart, Firebase, Flutter, Git, GitHub, iOS, REST API, UI & UX Design",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-flutter-development-internship-at-lazydeveloper-teched-pvt-ltd1757066882"
  },
  {
    "Organization / Company": "Indic Inspirations India",
    "Program Details": "Product Design Internship: Create products in wood, metal, ceramics, and grass craft using design/rendering tools, demonstrate teamwork and communication skills.",
    "Location": "Pune, India",
    "Duration": "6 Months",
    "Stipend": "₹9,000 - 10,000/month",
    "Eligibility Criteria": "Pursuing or completed relevant education, interest in product design.",
    "Skill Requirements": "Adobe Photoshop, Autodesk Fusion 360, Design Thinking, Rhino",
    "Perks & Benefits": "Certificate, Flexible hours, 5-day workweek",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "Apply Here"
  },
  {
    "Organization / Company": "SEOValley Solutions",
    "Program Details": "PHP Development Internship: Develop and maintain websites using PHP, WordPress, and MySQL, implement SEO recommendations, optimize website architecture, and follow W3C standards.",
    "Location": "Work from home",
    "Duration": "2 Months",
    "Stipend": "₹10,000 - 20,000/month",
    "Eligibility Criteria": "Experience in web technologies (HTML, CSS, JavaScript, PHP, WordPress), SEO knowledge, English proficiency.",
    "Skill Requirements": "Blogging, CodeIgniter, Creative Writing, English Proficiency (Spoken), HTML, JavaScript, jQuery, MySQL, PHP, SEO, WordPress",
    "Perks & Benefits": "None specified",
    "Mode / Work Type": "Part-time, Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-php-development-internship-at-seovalley-solutions-private-limited1757061116"
  },
  {
    "Organization / Company": "CCBUL",
    "Program Details": "Mobile App Development Internship: Develop mobile apps using Flutter, integrate Firebase and REST APIs, design user-friendly interfaces, test, and deploy to app stores.",
    "Location": "Work from home",
    "Duration": "3 Months",
    "Stipend": "₹5,000/month",
    "Eligibility Criteria": " Knowledge of PHP and REST API, interest in mobile app development.",
    "Skill Requirements": "Android, Flutter, MySQL, PHP, REST API",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-mobile-app-development-internship-at-ccbul1757060830"
  },
  {
    "Organization / Company": "Bricks 4 Kidz",
    "Program Details": "Robotics Internship: Deliver robotics and programming lessons for ages 4-12 using Bee-Bots, Dash & Dot, Scratch Jr, prepare content, assess progress, and maintain materials.",
    "Location": "Delhi, India (Hybrid)",
    "Duration": "4 Months",
    "Stipend": "₹2,710 - 2,811/week (Fixed: ₹2,700 - 2,800 + Incentive: ₹10 - 11)",
    "Eligibility Criteria": " Interest in teaching robotics to children.",
    "Skill Requirements": "Artificial Intelligence, C Programming, Python, Robotics",
    "Perks & Benefits": "Letter of recommendation, Flexible hours",
    "Mode / Work Type": "Part-time, Hybrid",
    "Application Link": "https://internshala.com/internship/detail/part-time-robotics-internship-in-delhi-at-bricks-4-kidz1757060826"
  },
  {
    "Organization / Company": "Crobstacle Ventures LLP",
    "Program Details": "WordPress Development",
    "Location": "Dehradun",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 4,500 – 10,000 /month (Fixed + Incentives) Job offer: ₹ 2 LPA post internship",
    "Eligibility Criteria": "From Dehradun only, Relevant skills/interests , Engg/CS/IT students or fresh graduates.",
    "Skill Requirements": "CSS, HTML, JavaScript, jQuery, MySQL, Node.js, PHP, React, SEO, WordPress",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Informal dress code, Job offer",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/wordpress-development-internship-in-dehradun-at-crobstacle-ventures-llp1757064244"
  },
  {
    "Organization / Company": "OTM",
    "Program Details": "Website & Social Media",
    "Location": "Delhi",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 10,000 – 10,500 /month",
    "Eligibility Criteria": "Relevant skills/interests",
    "Skill Requirements": "Canva, Facebook Ads, Image Editing, Instagram Marketing, Shopify",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Informal dress code",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/website-social-media-internship-in-delhi-at-abhas-gupta1757064564"
  },
  {
    "Organization / Company": "SENTRIVE",
    "Program Details": "Mobile App Development",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 1,000 – 2,000 /month",
    "Eligibility Criteria": "Relevant skills/interests",
    "Skill Requirements": "Android, Bubble.io, Firebase, Flutter, iOS, Java, Kotlin, Node.js, React, React Native, REST API",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible work hours",
    "Mode / Work Type": "Remote / Part-time",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-mobile-app-development-internship-at-sentrive1757064253"
  },
  {
    "Organization / Company": "AVM Healthcare Products Private Limited",
    "Program Details": "Mechanical Engineering",
    "Location": "Delhi, Gurgaon",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 15,000 – 20,000 /month",
    "Eligibility Criteria": "Relevant skills/interests ,Bachelor’s degree in Mechanical Engineering (Master’s preferred)",
    "Skill Requirements": "Computer Skills, MS-Excel, MS-Office, CAD, CAM, CORAL",
    "Perks & Benefits": "Free snacks & beverages",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/mechanical-engineering-internship-in-multiple-locations-at-avm-healthcare-products-private-limited1757061030"
  },
  {
    "Organization / Company": "Legacy",
    "Program Details": "Android App Development",
    "Location": "Work from Home",
    "Duration": "2 Months (Start: Immediately)",
    "Stipend": "₹ 1,000 – 2,000 /month",
    "Eligibility Criteria": "Relevant skills/interests, CS/IT students preferred",
    "Skill Requirements": "Angular, Django Rest Framework, JavaScript, Python, REST API, SQL",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible work hours",
    "Mode / Work Type": "Part-time, Work from Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-android-app-development-internship-at-legacy1757060502"
  },
  {
    "Organization / Company": "Cubastion Consulting Private Limited",
    "Program Details": "Information Technology",
    "Location": "Gurgaon",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹ 15,000 – 20,000 /month",
    "Eligibility Criteria": "Relevant skills/interests, Pursuing degree in CS, IT, or related field",
    "Skill Requirements": "Computer Networking, DNS, Firewall Configuration, LAN, Linux, TCP/IP, WAN, Windows",
    "Perks & Benefits": "None specified",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/information-technology-internship-in-gurgaon-at-cubastion-consulting-private-limited1757059410"
  },
  {
    "Organization / Company": "Bikanervala Foods Private Limited",
    "Program Details": "Quality Analyst",
    "Location": "Delhi, Mumbai, Sonepat, Telangana",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹ 15,000 /month",
    "Eligibility Criteria": "B.Sc. in Food Technology completed or pursuing, Relevant skills/interests",
    "Skill Requirements": "Food Safety, Quality Assurance/Quality Control (QA/QC)",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Full-time, In-office",
    "Application Link": "https://internshala.com/internship/detail/quality-analyst-internship-in-multiple-locations-at-bikanervala-foods-private-limited1757055091"
  },
  {
    "Organization / Company": "Pro India",
    "Program Details": "Sustainability",
    "Location": "Work from Home",
    "Duration": "4 Months (Start: Immediately)",
    "Stipend": "₹ 4,000 /month (Fixed: ₹ 2,000 + Incentive: ₹ 2,000) Job offer: ₹ 3–4.5 LPA post internship",
    "Eligibility Criteria": "Relevant skills/interests, Passion for ESG domain",
    "Skill Requirements": "Community Management, Effective Communication",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible work hours, 5-day work week, Job offer",
    "Mode / Work Type": "Part-time, Work from Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-sustainability-internship-at-pro-india1757054780"
  },
  {
    "Organization / Company": "Pro India",
    "Program Details": "Web Development",
    "Location": "Work from Home",
    "Duration": "4 Months (Start: Immediately)",
    "Stipend": "₹ 2,000 – 5,000 /month Job offer: ₹ 2–3 LPA post internship",
    "Eligibility Criteria": "Relevant skills/interests",
    "Skill Requirements": "HTML, MySQL, PHP, WordPress",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible work hours, 5-day work week, Job offer",
    "Mode / Work Type": "Part-time, Work from Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-web-development-internship-at-pro-india1757054498"
  },
  {
    "Organization / Company": "Lalit Bohra",
    "Program Details": "Search Engine Optimization (SEO)",
    "Location": "Work from Home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 1,000 /month Job offer: ₹ 2.2–3 LPA post internship",
    "Eligibility Criteria": "Relevant skills/interests , 12th-pass or current college students",
    "Skill Requirements": "Digital Marketing, Email Marketing, Google Analytics, SEM, SEO, Social Media Marketing, WordPress",
    "Perks & Benefits": "Certificate, Letter of Recommendation, Flexible work hours, Job offer",
    "Mode / Work Type": "Work from Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-search-engine-optimization-seo-internship-at-lalit-bohra1757053369"
  },
  {
    "Organization / Company": "Brain Quest",
    "Program Details": "WordPress & PHP Developer",
    "Location": "Work from Home",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹ 5,000 – 7,000 /month",
    "Eligibility Criteria": "Relevant skills/interests",
    "Skill Requirements": "WordPress, WooCommerce, HTML, CSS, JavaScript, Basic PHP",
    "Perks & Benefits": "Certificate, 5-day work week",
    "Mode / Work Type": "Work from Home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-wordpress-php-developer-internship-at-brain-quest1757051050"
  },
  {
    "Organization / Company": "Futurism Technologies",
    "Program Details": "Cyber Security",
    "Location": "Pune",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 5,000 – 15,000 /month",
    "Eligibility Criteria": "Relevant skills/interests,  Freshers welcome, final-year B.Tech/BCA/MCA (CSE, IT, ECE), or non-tech with interest",
    "Skill Requirements": "Computer skills, Ethical Hacking",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/cyber-security-internship-in-pune-at-futurism-technologies1757049137"
  },
  {
    "Organization / Company": "AVM Healthcare Products Private Limited",
    "Program Details": "Instrumentation and Control Engineering",
    "Location": "Delhi, Gurgaon",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹ 5,000 – 10,000 /month",
    "Eligibility Criteria": "Relevant skills/interests, Mechanical engineering degree preferred",
    "Skill Requirements": "Computer skills, Mechanical & Electrical Product Design, CATIA, SolidWorks, MS-Excel",
    "Perks & Benefits": "Free snacks & beverages",
    "Mode / Work Type": "Full-time, On-site",
    "Application Link": "https://internshala.com/internship/detail/instrumentation-and-control-engineering-internship-in-multiple-locations-at-avm-healthcare-products-private-limited1757049616"
  },
  {
    "Organization / Company": "Achieve Point Private Limited",
    "Program Details": "XML Conversion Specialist",
    "Location": "Work from home",
    "Duration": "2 Months (Start: Immediately)",
    "Stipend": "₹ 6,000 – 12,000 /month",
    "Eligibility Criteria": "Relevant skills/interests ,Strong knowledge of JATS XML (NLM 1.3) standards, Experience in journal article structuring and tagging",
    "Skill Requirements": "HTML, XML, JATS XML knowledge, Academic Publishing",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-xml-conversion-specialist-internship-at-achieve-point-private-limited1757049502"
  },
  {
    "Organization / Company": "Humanity Founders",
    "Program Details": "AI Full Stack Engineer",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 8,000 – 15,000 /month",
    "Eligibility Criteria": "Relevant skills/interests",
    "Skill Requirements": "AIML, ChatGPT, LLM evaluation, NLP, Neural Networks, Next.js, Node.js, PostgreSQL, Prompt Engineering, Python, React, REST API, SQLite",
    "Perks & Benefits": "Certificate, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-ai-full-stack-engineer-internship-at-humanity-founders1757048434"
  },
  {
    "Organization / Company": "AppSynergies Private Limited",
    "Program Details": "AI/ML",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹ 5,000 – 10,000 /month",
    "Eligibility Criteria": "Relevant skills/interests, BTech in CS or equivalent experience",
    "Skill Requirements": "Flask, Machine Learning, Python, SQL",
    "Perks & Benefits": "Certificate, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-ai-ml-internship-at-appsynergies-private-limited1757048372"
  },
  {
    "Organization / Company": "Omega Capital Limited (Dubai, UAE)",
    "Program Details": "Senior Full-Stack Developer",
    "Location": "Dubai, United Arab Emirates",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "$1,000 – $1,500 /month",
    "Eligibility Criteria": " Relevant skills/interests ",
    "Skill Requirements": "A/B Testing, Data Visualization, WebSockets",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/senior-full-stack-developer-internship-in-dubai-at-omega-capital-limited1757047518"
  },
  {
    "Organization / Company": "Yasham Software Services Private Limited",
    "Program Details": "Flutter Development",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹10,000 /month",
    "Eligibility Criteria": " Relevant skills/interests ",
    "Skill Requirements": "Dart, Flutter, Firebase, Laravel, REST API, UI & UX Design",
    "Perks & Benefits": "Certificate, Letter of recommendation",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-flutter-development-internship-at-yasham-software-services-private-limited1757047308"
  },
  {
    "Organization / Company": "Optimasys",
    "Program Details": "Python Development",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹15,000 - 25,000 /month",
    "Eligibility Criteria": " Relevant skills/interests  ",
    "Skill Requirements": "Python, Django, Flask, HTML, CSS, REST API, Machine Learning",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-python-development-internship-at-optimasys1757041236"
  },
  {
    "Organization / Company": "Optimasys",
    "Program Details": "Java Development",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹15,000 - 25,000 /month",
    "Eligibility Criteria": " Relevant skills/interests ",
    "Skill Requirements": "Java, J2EE, JSP, Hibernate ORM, Spring MVC, MySQL",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-java-development-internship-at-optimasys1757041168"
  },
  {
    "Organization / Company": "Humans Of EV",
    "Program Details": "Internet Of Things (IoT)",
    "Location": "Delhi",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹7,000 - 10,000 /month",
    "Eligibility Criteria": " Relevant skills/interests",
    "Skill Requirements": "C++, Python, IoT, Raspberry Pi, VLSI",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/internet-of-things-iot-internship-in-delhi-at-humans-of-ev1756994497"
  },
  {
    "Organization / Company": "Amrata",
    "Program Details": "Web Development",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹15,000 - 25,000 /month",
    "Eligibility Criteria": " Relevant skills/interests ",
    "Skill Requirements": "PHP, MySQL, HTML, CSS, JavaScript, jQuery, WordPress, Bootstrap, Node.js",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-web-development-internship-at-amrata1757039875"
  },
  {
    "Organization / Company": "Dwarka Jewel",
    "Program Details": "Jewellery Designer",
    "Location": "Jaipur",
    "Duration": "2 Months (Start: Immediately)",
    "Stipend": "₹5,000 - 7,000 /month",
    "Eligibility Criteria": " Relevant skills/interests",
    "Skill Requirements": "CAD, Design System",
    "Perks & Benefits": "Certificate, Letter of recommendation, 5-day work week",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/jewellery-designer-internship-in-jaipur-at-dwarka-jewel1756990203"
  },
  {
    "Organization / Company": "Refresh Kid LLC",
    "Program Details": "Teaching",
    "Location": "Milwaukee, United States (Work from home)",
    "Duration": "6 Months (Part-time, Start: Immediately)",
    "Stipend": "₹10,000 - 12,000 /month",
    "Eligibility Criteria": " Relevant skills/interests",
    "Skill Requirements": "Python, HTML, Java, JavaScript, CodeIgniter, Computer Networking, Online Teaching, Content Writing, English Proficiency (Spoken & Written), Teaching",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours",
    "Mode / Work Type": "Work from home (Part-time)",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-teaching-internship-at-refresh-kid-llc1756989599"
  },
  {
    "Organization / Company": "Zestorm Technologies Private Limited",
    "Program Details": "Dotnet Fullstack Developer For Internship With Pre Placement Offer",
    "Location": "Pune, Maharashtra",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹8,000 - 10,000 /month",
    "Eligibility Criteria": " Appearing final year MCA / MCS, Relevant skills and interests",
    "Skill Requirements": ".NET, C#.NET, ASP.NET, Angular 7.0, MVC, HTML5, CSS3, JavaScript, JQuery, OOP, SQL",
    "Perks & Benefits": "Certificate, Informal dress code, 5 days a week",
    "Mode / Work Type": "In-office (Full-time)",
    "Application Link": "https://internshala.com/internship/detail/dotnet-fullstack-developer-for-internship-with-pre-placement-offer-internship-in-multiple-locations-at-zestorm-technologies-private-limited1756988979"
  },
  {
    "Organization / Company": "Kori AI",
    "Program Details": "iOS App Development Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹20,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "iOS, Swift, Xcode, SwiftUI, SwiftData, MVVM, concurrent programming",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-ios-app-development-internship-at-kori-ai1756988442"
  },
  {
    "Organization / Company": "Acmedian",
    "Program Details": "Software Testing Internship",
    "Location": "Chandigarh",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹5,000 - 7,000 /month",
    "Eligibility Criteria": "Relevant skills and interests",
    "Skill Requirements": "Jira, Manual Testing",
    "Perks & Benefits": "Letter of recommendation, 5 days a week",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/software-testing-internship-in-chandigarh-at-acmedian1756985466"
  },
  {
    "Organization / Company": "The Innovation Story",
    "Program Details": "Robotics Design Engineer and Mentor",
    "Location": "Mumbai",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹7,000 - 12,000 /month",
    "Eligibility Criteria": "Relevant skills and interests, Experience in robotics competitions (Robocon, eYantra, Racing, Drones, etc.)",
    "Skill Requirements": "3D Printing, CAD, Design Thinking, Robotics, SolidWorks",
    "Perks & Benefits": "Certificate, Letter of recommendation, Informal dress code",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/robotics-design-engineer-and-mentor-internship-in-mumbai-at-the-innovation-story1756982013"
  },
  {
    "Organization / Company": "Advantage",
    "Program Details": "Civil Engineering Internship",
    "Location": "Dewas",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹10,000 /month",
    "Eligibility Criteria": " Relevant skills and interests,Women candidates with Civil/Architecture background preferred",
    "Skill Requirements": "AutoCAD, Autodesk Revit, CorelDRAW, Design Thinking, Rhino",
    "Perks & Benefits": "Certificate, Flexible work hours, Informal dress code, Job offer post-internship (₹3.5–6 LPA)",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/civil-engineering-internship-in-dewas-at-advantage1756971911"
  },
  {
    "Organization / Company": "Skyline Space",
    "Program Details": "Aerospace Engineering Internship",
    "Location": "Work from home",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹6,000 - 8,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "ANSYS, CATIA, MATLAB, SolidWorks",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-aerospace-engineering-internship-at-skyline-space1756971427"
  },
  {
    "Organization / Company": "Nexium Media",
    "Program Details": "WordPress Developer Internship",
    "Location": "Work from home",
    "Duration": "4 Months (Start: Immediately)",
    "Stipend": "₹5,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "CMS, CSS, Design System, HTML, WordPress",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, Job offer (₹3 LPA post internship)",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-wordpress-developer-internship-at-nexium-media1756975383"
  },
  {
    "Organization / Company": "XivTech",
    "Program Details": "DevOps Engineer Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹10,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "AWS, Docker, Jenkins, Kubernetes, Prometheus, Terraform",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-devops-engineer-internship-at-xivtech1756969332"
  },
  {
    "Organization / Company": "Janitri Innovations Private Limited",
    "Program Details": "QA Testing Internship",
    "Location": "Bangalore",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹15,000 - 20,000 /month",
    "Eligibility Criteria": " Relevant skills and interests, Bachelor’s in CS or related field • 0-1 year experience",
    "Skill Requirements": "Java, SQL",
    "Perks & Benefits": "Certificate, Job offer (₹4-5 LPA post internship)",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/qa-testing-internship-in-bangalore-at-janitri-innovations-private-limited1756968678"
  },
  {
    "Organization / Company": "Anshumat Foundation",
    "Program Details": "Full Stack Development Internship (with PPO)",
    "Location": "Durgapur, Bangalore (Hybrid)",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "Unpaid (Stipend + PPO post evaluation)",
    "Eligibility Criteria": "Relevant skills and interests, Strong sense of ownership, punctuality, problem-solving mindset",
    "Skill Requirements": "AWS, AngularJS, Backend & Frontend Development, Bubble.io, CSS, DevOps, DigitalOcean, GCP, HTML, JavaScript, MongoDB, MySQL, Node.js, PHP, Python, React, Web Development",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, Informal dress code, Job offer (₹3-10 LPA post internship)",
    "Mode / Work Type": "Hybrid",
    "Application Link": "https://internshala.com/internship/detail/full-stack-development-internship-in-multiple-locations-at-anshumat-foundation1756968067"
  },
  {
    "Organization / Company": "Digital Heroes",
    "Program Details": "Shopify Development Internship (Part-time)",
    "Location": "Lucknow",
    "Duration": "1 Month (Start: Immediately)",
    "Stipend": "₹4,000 – 12,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Shopify, Liquid, HTML, CSS, JavaScript",
    "Perks & Benefits": "Certificate, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/part-time-shopify-development-internship-in-lucknow-at-digital-heroes1756965855"
  },
  {
    "Organization / Company": "HLSR Technologies (Ask IRa)",
    "Program Details": "Front End Development Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹10,001 – 14,000 /month (Fixed ₹10,000–12,000 + Incentive ₹1–2,000)",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "React Native",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-front-end-development-internship-at-hlsr-technologies-ask-ira1756964588"
  },
  {
    "Organization / Company": "Lawtech",
    "Program Details": "Backend Development Internship",
    "Location": "Work from home",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹12,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Claude, C Programming, Django, HTML, Java, Kaggle, LLM evaluation, Machine Learning, MySQL, Node.js, OpenAI API, Python, REST API",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-backend-development-internship-at-lawtech1756964340"
  },
  {
    "Organization / Company": "Technocrypt Private Limited",
    "Program Details": "WordPress Development Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹11,000 – 16,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "CSS, HTML, JavaScript, PHP, WordPress",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-wordpress-development-internship-at-technocrypt-private-limited1756964206"
  },
  {
    "Organization / Company": "Quantazone",
    "Program Details": "WordPress Development Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹5,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "WordPress, HTML, CSS, PHP, SEO, SEM, Canva, AI Image/Video Generation, Web development, Effective communication",
    "Perks & Benefits": "Certificate, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-wordpress-development-internship-at-quantazone1756963893"
  },
  {
    "Organization / Company": "Better",
    "Program Details": "Software Engineering Internship (Python, React)",
    "Location": "Work from home",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹8,000 – 10,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Python, Flask, React (TypeScript), SQL/NoSQL, REST APIs, Agile workflow",
    "Perks & Benefits": "Certificate, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-software-engineering-python-react-internship-at-better1756961525"
  },
  {
    "Organization / Company": "TheBlackJabGroup",
    "Program Details": "Shopify Web Developer Internship",
    "Location": "Work from home",
    "Duration": "4 Months (Start: Immediately)",
    "Stipend": "₹10,000 – 30,000 /month",
    "Eligibility Criteria": " Relevant skills and interests, Computer Science degree",
    "Skill Requirements": "CSS, Git, HTML, JavaScript, Node.js, React Native",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-shopify-web-developer-internship-at-theblackjabgroup1756959695"
  },
  {
    "Organization / Company": "Digital Heroes",
    "Program Details": "Web Development Internship",
    "Location": "Work from home",
    "Duration": "1 Month (Start: Immediately)",
    "Stipend": "₹2,000 – 5,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Web development",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-web-development-internship-at-digital-heroes1756928249"
  },
  {
    "Organization / Company": "Digital Heroes",
    "Program Details": "Software Development Engineering (Web) Internship",
    "Location": "Work from home",
    "Duration": "1 Month (Start: Immediately)",
    "Stipend": "₹15,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "SDLC, basic Python/C/Java knowledge",
    "Perks & Benefits": "Certificate, Flexible hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-software-development-engineering-web-internship-at-digital-heroes1756928246"
  },
  {
    "Organization / Company": "Digital Heroes",
    "Program Details": "Web Development (Shopify) Internship",
    "Location": "Work from home",
    "Duration": "1 Month (Start: Immediately)",
    "Stipend": "₹15,000 /month",
    "Eligibility Criteria": "Relevant skills and interests",
    "Skill Requirements": "Shopify, Liquid, HTML, CSS, JavaScript, RDP familiarity",
    "Perks & Benefits": "Certificate, Flexible hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-web-development-internship-at-digital-heroes1756928239"
  },
  {
    "Organization / Company": "Krid.AI",
    "Program Details": "Agentic AI Internship",
    "Location": "Gurgaon (Hybrid)",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹5,000 - 15,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Python, LangChain, LLM evaluation",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible hours, Informal dress code, 5 days a week",
    "Mode / Work Type": "Hybrid",
    "Application Link": "https://internshala.com/internship/detail/agentic-ai-internship-in-gurgaon-at-kridai1756906322"
  },
  {
    "Organization / Company": "Leap Robots",
    "Program Details": "Robotics Trainer Internship",
    "Location": "Hyderabad",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹10,000 - 12,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Arduino, C Programming, Embedded Systems, IoT, Raspberry Pi",
    "Perks & Benefits": "Certificate, Letter of recommendation, Free snacks & beverages",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/robotics-trainer-internship-in-hyderabad-at-leap-robots1756905518"
  },
  {
    "Organization / Company": "Scaler",
    "Program Details": "Product Analytics Internship",
    "Location": "Bangalore",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹30,000 - 35,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Power BI, Python, SQL",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, Informal dress code, 5 days a week, Free snacks & beverages",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/product-analytics-internship-in-bangalore-at-scaler1756904167"
  },
  {
    "Organization / Company": "Shiplee",
    "Program Details": "Full Stack Development (MERN Migration) Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹2,000 - 3,000 /month",
    "Eligibility Criteria": "Relevant skills and interests",
    "Skill Requirements": "JavaScript, React, Node.js, Express.js, MySQL, PHP",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-full-stack-development-mern-migration-internship-at-shiplee1756901992"
  },
  {
    "Organization / Company": "Solvitude",
    "Program Details": "Transcription QA Expert (Hindi Language) Internship",
    "Location": "Work from home",
    "Duration": "1 Month (Start: Immediately)",
    "Stipend": "₹10,000 - 25,000 /month",
    "Eligibility Criteria": "Relevant skills and interests ,Minimum 6 hours/day commitment",
    "Skill Requirements": "Hindi Proficiency (Spoken & Written), MS-Excel, Google Sheets, Proofreading, Quality Assurance (QA/QC), Content Writing, English Proficiency",
    "Perks & Benefits": "Certificate, Letter of recommendation",
    "Mode / Work Type": "Work from home (Part-time)",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-transcription-qa-expert-hindi-language-internship-at-solvitude1756901848"
  },
  {
    "Organization / Company": "Formial Labs",
    "Program Details": "Pharmaceutical Internship",
    "Location": "Bangalore",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹15,000 - 20,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Biology, Chemistry, Pharmacology, Pharmacovigilance, MS-Excel, Problem Solving, Interpersonal Skills",
    "Perks & Benefits": "Certificate, Letter of recommendation, Informal dress code, Job offer post internship (₹3–3.5 LPA)",
    "Mode / Work Type": "In-office (Full-time)",
    "Application Link": "https://internshala.com/internship/detail/pharmaceutical-internship-in-bangalore-at-formial-labs1756901149"
  },
  {
    "Organization / Company": "Adornment Engineers India Private Limited",
    "Program Details": "Mechanical Engineering Internship",
    "Location": "Faridabad (Hybrid)",
    "Duration": "6 Months (Start: Immediately)",
    "Stipend": "₹5,000 - 12,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "AutoCAD",
    "Perks & Benefits": "Certificate, Letter of recommendation, Free snacks & beverages",
    "Mode / Work Type": "In-office / Hybrid",
    "Application Link": "https://internshala.com/internship/detail/mechanical-engineering-internship-in-faridabad-at-adornment-engineers-india-private-limited1756881033"
  },
  {
    "Organization / Company": "StepSTEM",
    "Program Details": "CAD Design Internship",
    "Location": "Work from home",
    "Duration": "2 Months (Start: Immediately)",
    "Stipend": "₹1,000 /month",
    "Eligibility Criteria": "Relevant skills and interests",
    "Skill Requirements": "Arduino, Autodesk Fusion 360, SolidWorks",
    "Perks & Benefits": "Certificate, Flexible work hours, 5 days a week",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-cad-design-internship-at-stepstem1756888572"
  },
  {
    "Organization / Company": "Capgen Services Private Limited",
    "Program Details": "IT & Networking Internship",
    "Location": "Bangalore",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹10,000 - 15,000 /month",
    "Eligibility Criteria": "Relevant skills and interests",
    "Skill Requirements": "Automation, Networking, Python, Technical Support, Windows",
    "Perks & Benefits": "Exposure to automation & development projects",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/it-networking-internship-in-bangalore-at-capgen-services-private-limited1756899140"
  },
  {
    "Organization / Company": "Brilliaskin Skincare Private Limited",
    "Program Details": "Web Development Internship",
    "Location": "Work from home",
    "Duration": "2 Months (Start: Immediately)",
    "Stipend": "₹5,000 - 10,000 /month",
    "Eligibility Criteria": "Relevant skills and interests",
    "Skill Requirements": "jQuery, Shopify",
    "Perks & Benefits": "Certificate",
    "Mode / Work Type": "Work from home",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-web-development-internship-at-brilliaskin-skincare-private-limited1756898657"
  },
  {
    "Organization / Company": "Fx31 Labs",
    "Program Details": "Robotics Internship",
    "Location": "Ahmedabad",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹5,000 - 6,000 /month",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Arduino, Raspberry Pi, Robotics, ROS, Mechanical & Electrical Product Design, AI",
    "Perks & Benefits": "Certificate, Flexible work hours, Informal dress code, 5 days a week, Free snacks & beverages",
    "Mode / Work Type": "In-office",
    "Application Link": "https://internshala.com/internship/detail/robotics-internship-in-ahmedabad-at-fx31-labs1756895835"
  },
  {
    "Organization / Company": "Abhijit Jha",
    "Program Details": "Mobile App Development Internship",
    "Location": "Work from home",
    "Duration": "3 Months (Start: Immediately)",
    "Stipend": "₹4,500 - 5,500 /month (Fixed + Incentives)",
    "Eligibility Criteria": " Relevant skills and interests",
    "Skill Requirements": "Android, iOS, Kotlin, Node.js, React, React Native, REST API",
    "Perks & Benefits": "Certificate, Letter of recommendation, Flexible work hours",
    "Mode / Work Type": "Work from home / Part-time",
    "Application Link": "https://internshala.com/internship/detail/work-from-home-part-time-mobile-app-development-internship-at-abhijit-jha1756893816"
  }
]

 export default data